### PR TITLE
Add java function to hello world

### PR DESCRIPTION
**Pull request by piumi96**

### CODE REVIEW

**Comment by DaylightFox** [comment]
Hey, there seems to be an issue with this PR, namely you accidentally deleted all the other files ;)

If you could amend this issue I'd be more than happy to merge this :)

**Comment by piumi96** [comment]
oh man really sorry about that. I'll fix it right away

**Comment by piumi96** [comment]
i seem to be having some problems with branching. sorry im a bit new to this :) could you help me out? im getting a message that there are untracked working trees and i can't figure out how to fix it.

**Comment by DaylightFox** [comment]
> i seem to be having some problems with branching. sorry im a bit new to this :) could you help me out? im getting a message that there are untracked working trees and i can't figure out how to fix it.

Hey no worries :)
I believe you might have a similar issues as detailed over [here](https://github.com/avast-tl/retdec/issues/92), try the solution posted by PeterMatula. Make sure to backup the script you've made before you do anything though, we don't want to lose that! :)

**Pull request closed without merging**
